### ISSUE TITLE
feat: allow attributes and ordering_key on typed (not raw) publish

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/pub-sub-client#5]
Currently only plain serializable messages are supported:

``` rust
// publisher/mod.rs
pub async fn publish<M: Serialize + Debug>(
    &self,
    topic_id: &str,
    messages: Vec<M>,
    timeout: Option<Duration>,
) -> Result<Vec<String>, Error>
```

**Comment by hseeberger** [comment]
Closed by #8

**Comment by codetestdeployrepeat** [comment]
@hseeberger can you share some snippets on setting attributes on when publishing the derived `PublishedMessage`?

I managed to publish my data (with custom structure) but I need to set some attributes.

Currently trying the raw message.

**Comment by hseeberger** [comment]
This is from `test.rs`:

```rust
    // Publish typed with attributes
    let messages = vec![(
        Message::Foo {
            text: TEXT.to_string(),
        },
        HashMap::from([("version".to_string(), "v1".to_string())]),
    )];
    let result = pub_sub_client
        .publish(TOPIC_ID, messages, None, Some(Duration::from_secs(10)))
        .await;
```

Does that help, @codetestdeployrepeat?

**Comment by codetestdeployrepeat** [comment]
@hseeberger that worked, thanks!

Noticed that there are some revamp on the latest version just recently, will check it out...
